site_name: CouponCodes
site_favicon: favicon.ico
repo_url: https://github.com/AngrySoundTech/CouponCodes3
theme: readthedocs

pages:
  - ['index.md', 'Home']
  - ['user-guide/installation.md', 'Installation']
  - ['developer-guide/api.md', 'API']
  - ['about/license.md', 'License']
