#
# This is the configuration for CouponCodes
# If you have questions about using this plugin, or what anything means, please feel free to ask on the BukkitDev page
# If you are receiving errors, please report it on BukkitDev. It really helps the development of this plugin.
#
# If you are interested in how this plugin works (code wise) you can view the source code from GitHub.
# You can also open an issue here for any feature requests / bug reporting.
# https://github.com/Drepic26/CouponCodes-Revived
#

# Language the plugin should use
# available languages are: en_US
locale: en_US

# sql-type should be either 'MySQL' or 'SQLite'
sql-type: SQLite

# Ignore these options if you are using SQLite
MySQL-options:
   hostname: localhost
   port: '3306'
   database: CouponCodes
   username: minecraft
   password: password

# This will decide to use vault or not. Leave false if you do not have vault enabled
use-vault: false

# Leave this true UNLESS you want to disable timed coupons
use-thread: true

# I recommend to leave this at false. Your console will be spammed with debug messages
debug: false

# Metrics collects information about CouponCodes, such as version and amount of coupons.
# If this is disabled, no info will be sent to http://mcstats.org/plugin/CouponCodes
use-metrics: true

# If set to false, the plugin will not update automatically
auto-update: true
