name: CouponCodes
author: AngrySoundTech
main: com.drevelopment.couponcodes.bukkit.BukkitPlugin
version: ${version}
softdepend: [Vault]
commands:
    coupon:
        description: CouponCode's main command
        usage: /<command>
permissions:
    cc.*:
        description: Gives access to all coupon commands
        children:
            cc.add: true
            cc.redeem: true
            cc.remove: true
            cc.list: true
            cc.reload: true
            cc.info: true
            cc.update: true
    cc.add:
        description: Allows you to add a coupon
        default: op
    cc.time:
        description: Allows you to change the time of a coupon
        default: op
    cc.uses:
        description: Allows you to change the uses of a coupon
        default: op
    cc.redeem:
        description: Allows you to redeem a coupon
        default: true
    cc.remove:
        description: Allows you to remove a coupon
        default: op
    cc.list:
        description: Allows you to see a list of all the coupons
        default: op
    cc.info:
        description: Allows you to view information on coupons
        default: op
    cc.update:
        description: Notifies you when there is an update
        default: op
    cc.reload:
        description: Allows you to reload the database
        default: op
