name: Coupon Codes
main: net.lala.CouponCodes.CouponCodes
version: 2.0.0
author: LaLa
softdepend: [Vault]
commands:
    c:
        alias: [coupon]
        description: CouponCode's main command
        usage: /<command>
permissions:
    cc.*:
        description: Gives access to all coupon commands
        children:
            cc.add: true
            cc.redeem: true
            cc.remove: true
            cc.list: true
    cc.add:
        description: Allows you to add a coupon
        default: false
    cc.redeem:
        description: Allows you to redeem a coupon
        default: false
    cc.remove:
        description: Allows you to remove a coupon
        default: false
    cc.list:
        description: Allows you to see a list of all the coupons
        default: false