name: Coupon Codes
main: net.lala.CouponCodes.CouponCodes
version: 2.0.0
author: LaLa
softdepend: [Vault]
commands:
    coupon:
        description: CouponCode's main command
        usage: /<command>
permissions:
    cc.*:
        description: Gives access to all coupon commands
        children:
            cc.add: true
            cc.redeem: true
            cc.remove: true
    coupon.add:
        description: Allows you to add a coupon
        default: false
    coupon.redeem:
        description: Allows you to redeem a coupon
        default: false
    coupon.remove:
        description: Allows you to remove a coupon
        default: false